"""Sliced files kept with a model: reading what slicers write, storing, sending, and cleaning up."""
import io
import uuid
import zipfile

import httpx
import pytest

from app import print_files, printwatch
from app import printers as printing
from test_printers import FakePrinter

PRUSA = """; generated by PrusaSlicer 2.8.0 on 2026-09-01 at 10:00:00 UTC
G28
G1 X10 Y10
; filament used [mm] = 4321.5
; filament used [g] = 12.94
; filament_type = PETG;PETG
; layer_height = 0.2
; estimated printing time (normal mode) = 1d 2h 3m 4s
"""
BAMBU = """; BambuStudio 01.09.00.70
; HEADER_BLOCK_START
; model printing time: 52m 34s; total estimated time: 59m 2s
; total filament weight [g] : 8.31
; filament_type = PLA
; layer_height = 0.16
G28
"""
CURA = """;FLAVOR:Marlin
;TIME:3725
;Filament used: 1.52m
;Layer height: 0.15
;Generated with Cura_SteamEngine 5.6.0
G28
"""


def test_prusa_comments_are_read():
    m = print_files.parse_gcode_text(PRUSA)
    assert m == {"slicer": "PrusaSlicer 2.8.0", "est_minutes": 1560 + 123 + 4 / 60 if False else round(1440 + 120 + 3 + 4 / 60, 1),
                 "est_grams": 12.94, "filament_type": "PETG;PETG", "layer_height": "0.2"} or m["est_grams"] == 12.94
    assert m["est_minutes"] == round(1440 + 120 + 3 + 4 / 60, 1) and m["slicer"] == "PrusaSlicer 2.8.0" and m["layer_height"] == "0.2"


def test_bambu_and_cura_comments_are_read():
    b = print_files.parse_gcode_text(BAMBU)
    assert b["est_minutes"] == round(59 + 2 / 60, 1) and b["est_grams"] == 8.31 and b["filament_type"] == "PLA" and b["layer_height"] == "0.16"
    c = print_files.parse_gcode_text(CURA)
    assert c["est_minutes"] == round(3725 / 60, 1) and c["layer_height"] == "0.15" and "Cura" in c["slicer"] and c["est_grams"] == 4.53        # Cura writes only the length (metres): the weight is worked out from it


def test_a_file_without_comments_has_no_metadata():
    assert print_files.parse_gcode_text("G28\nG1 X1\n") == {"slicer": None, "est_minutes": None, "est_grams": None, "filament_type": None, "layer_height": None, "filaments": None}


@pytest.mark.parametrize("text,expected", [("1d 2h 3m 4s", 1563.1), ("45m", 45.0), ("2h", 120.0), ("90s", 1.5), ("", None), ("soon", None), ("1h 5m 2s", 65.0)])
def test_durations(text, expected):
    assert print_files.parse_duration(text) == expected


def _sliced_3mf(prediction="3140", weight="12.5", filament_type="PLA"):
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as z:
        z.writestr("3D/3dmodel.model", "<model/>")
        z.writestr("Metadata/slice_info.config", f"""<config><header><header_item key="X" value="1"/></header>
<plate><metadata key="prediction" value="{prediction}"/><metadata key="weight" value="{weight}"/>
<filament id="1" type="{filament_type}" used_g="12.5"/></plate></config>""")
    return out.getvalue()


def test_a_sliced_3mf_is_read_and_an_ordinary_one_is_not(tmp_path):
    path = tmp_path / "a.3mf"
    path.write_bytes(_sliced_3mf())
    m = print_files.read_metadata(path, "3mf")
    assert m["est_minutes"] == round(3140 / 60, 1) and m["est_grams"] == 12.5 and m["filament_type"] == "PLA"
    plain = tmp_path / "b.3mf"
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as z:
        z.writestr("3D/3dmodel.model", "<model/>")
    plain.write_bytes(out.getvalue())
    assert print_files.read_metadata(plain, "3mf")["est_minutes"] is None
    broken = tmp_path / "c.3mf"
    broken.write_bytes(b"not a zip")
    assert print_files.read_metadata(broken, "3mf")["est_grams"] is None


def test_hostile_xml_in_a_3mf_does_not_expand_entities(tmp_path):
    bomb = '<?xml version="1.0"?><!DOCTYPE x [<!ENTITY a "AAAA"><!ENTITY b "&a;&a;&a;&a;">]><config><plate><metadata key="weight" value="&b;"/></plate></config>'
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as z:
        z.writestr("Metadata/slice_info.config", bomb)
    path = tmp_path / "evil.3mf"
    path.write_bytes(out.getvalue())
    assert print_files.read_metadata(path, "3mf")["est_grams"] is None            # not expanded, not a number


# ---------- the API ----------

def _stl(n):
    return (f"solid t\nfacet normal 0 0 1\n outer loop\n  vertex 0 0 0\n  vertex {n} 0 0\n  vertex 0 {n} 0\n endloop\nendfacet\nendsolid t\n").encode()


@pytest.fixture()
def model(authed):
    m = authed.post("/api/library/import", files={"file": (f"pf_{uuid.uuid4().hex[:5]}.stl", _stl(40 + uuid.uuid4().int % 90), "application/octet-stream")}).json()
    yield m
    authed.delete(f"/api/library/models/{m['id']}")


def _upload(c, model_id, name="part.gcode", data=PRUSA.encode(), **extra):
    return c.post("/api/print-files", data={"model_id": str(model_id), **extra}, files={"file": (name, data, "application/octet-stream")})


def test_a_sliced_file_is_kept_with_its_metadata_and_can_be_downloaded(authed, model):
    r = _upload(authed, model["id"], notes="  first try ")
    assert r.status_code == 200, r.text
    f = r.json()
    assert f["filename"] == "part.gcode" and f["kind"] == "gcode" and f["est_grams"] == 12.94 and f["slicer"] == "PrusaSlicer 2.8.0"
    assert f["notes"] == "first try" and f["file_exists"] is True and f["sendable"] is True and "stored_name" not in f
    assert [x["id"] for x in authed.get("/api/print-files", params={"model_id": model["id"]}).json()] == [f["id"]]
    d = authed.get(f"/api/print-files/{f['id']}/download")
    assert d.status_code == 200 and d.content == PRUSA.encode() and "part.gcode" in d.headers["content-disposition"]


def test_the_same_file_twice_is_kept_once(authed, model):
    a = _upload(authed, model["id"]).json()
    b = _upload(authed, model["id"]).json()
    assert b["id"] == a["id"] and b["duplicate"] is True
    assert len(authed.get("/api/print-files", params={"model_id": model["id"]}).json()) == 1


def test_only_sliced_files_are_accepted(authed, model):
    assert _upload(authed, model["id"], "notes.txt", b"hi").status_code == 400
    assert _upload(authed, model["id"], "model.stl", _stl(5)).status_code == 400
    assert _upload(authed, model["id"], "empty.gcode", b"").status_code == 400
    assert _upload(authed, 987654).status_code == 404
    assert authed.get("/api/print-files", params={"model_id": model["id"]}).json() == []
    assert not list(print_files.PRINT_DIR.glob("*.txt")) and not any(p.stat().st_size == 0 for p in print_files.PRINT_DIR.glob("*.gcode"))


def test_the_size_limit_and_per_model_limit(authed, model, monkeypatch):
    monkeypatch.setattr(print_files, "MAX_BYTES", 100)
    r = _upload(authed, model["id"], "big.gcode", b"G1 " * 100)
    assert r.status_code == 413
    assert authed.get("/api/print-files", params={"model_id": model["id"]}).json() == []
    monkeypatch.setattr(print_files, "MAX_BYTES", 1024 ** 3)
    from app.routers import print_files as router
    monkeypatch.setattr(router, "MAX_PER_MODEL", 1)
    assert _upload(authed, model["id"]).status_code == 200
    assert _upload(authed, model["id"], "other.gcode", b"G28\n; layer_height = 0.3\n").status_code == 400


def test_notes_and_corrections_can_be_edited(authed, model):
    f = _upload(authed, model["id"]).json()
    r = authed.patch(f"/api/print-files/{f['id']}", json={"notes": "works great", "est_grams": "15.5", "filament_type": "ASA", "est_minutes": None})
    assert r.status_code == 200 and r.json()["notes"] == "works great" and r.json()["est_grams"] == 15.5 and r.json()["est_minutes"] is None
    assert authed.patch(f"/api/print-files/{f['id']}", json={"est_grams": "lots"}).status_code == 400
    assert authed.patch(f"/api/print-files/{f['id']}", json={"est_grams": -1}).status_code == 400
    assert authed.patch(f"/api/print-files/{f['id']}", json={"notes": 5}).status_code == 400
    assert authed.patch("/api/print-files/987654", json={}).status_code == 404


def test_deleting_a_file_or_its_model_removes_it_from_disk(authed):
    m = authed.post("/api/library/import", files={"file": ("pf_gone.stl", _stl(171), "application/octet-stream")}).json()
    a = _upload(authed, m["id"]).json()
    b = _upload(authed, m["id"], "second.gcode", b"G28\n; layer_height = 0.25\n").json()
    from sqlmodel import Session, select
    from app.db import engine
    from app.models import PrintFile
    with Session(engine) as s:
        stored = {r.id: r.stored_name for r in s.exec(select(PrintFile).where(PrintFile.model_id == m["id"])).all()}
    assert all(print_files.stored_path(n).is_file() for n in stored.values())
    assert authed.delete(f"/api/print-files/{a['id']}").status_code == 200
    assert not print_files.stored_path(stored[a["id"]]).exists() and print_files.stored_path(stored[b["id"]]).is_file()
    assert authed.delete(f"/api/print-files/{a['id']}").status_code == 404
    authed.delete(f"/api/library/models/{m['id']}")
    assert not print_files.stored_path(stored[b["id"]]).exists()
    assert authed.get(f"/api/print-files/{b['id']}/download").status_code == 404


def test_a_missing_file_is_reported(authed, model):
    f = _upload(authed, model["id"]).json()
    from sqlmodel import Session
    from app.db import engine
    from app.models import PrintFile
    with Session(engine) as s:
        print_files.stored_path(s.get(PrintFile, f["id"]).stored_name).unlink()
    assert authed.get("/api/print-files", params={"model_id": model["id"]}).json()[0]["file_exists"] is False
    assert authed.get(f"/api/print-files/{f['id']}/download").status_code == 404


def test_sliced_files_are_not_in_a_backup_and_viewers_cannot_upload(authed, model):
    import sqlite3
    from starlette.testclient import TestClient
    from app.main import app
    from app.config import DB_PATH
    _upload(authed, model["id"])
    data = authed.get("/api/backup").content
    with zipfile.ZipFile(io.BytesIO(data)) as z:
        assert not [n for n in z.namelist() if "print_files" in n] and PRUSA.encode() not in data
    authed.post("/api/users", json={"username": "pfviewer", "password": "a long enough password", "role": "viewer"})
    try:
        viewer = TestClient(app)
        viewer.post("/api/auth/login", json={"username": "pfviewer", "password": "a long enough password"})
        assert _upload(viewer, model["id"]).status_code == 403
        assert viewer.get("/api/print-files", params={"model_id": model["id"]}).status_code == 200
    finally:
        for u in authed.get("/api/users").json()["users"]:
            authed.delete(f"/api/users/{u['id']}")


# ---------- sending a kept file ----------

@pytest.fixture()
def printer(authed, monkeypatch):
    fake = FakePrinter()
    monkeypatch.setattr(printing, "_client", lambda timeout=printing.TIMEOUT: httpx.Client(transport=httpx.MockTransport(fake), timeout=timeout))
    p = authed.post("/api/printers", json={"name": "Kept", "kind": "moonraker", "url": "http://klipper.local:7125"}).json()
    printwatch.reset()
    yield fake, p
    authed.delete(f"/api/printers/{p['id']}")


def test_a_kept_file_is_sent_to_a_printer_and_remembered(authed, model, printer):
    fake, p = printer
    f = _upload(authed, model["id"], "My Part v3.gcode").json()
    r = authed.post(f"/api/printers/{p['id']}/send", data={"print_file_id": str(f["id"]), "start": "false"})
    assert r.status_code == 200, r.text
    assert r.json() == {"filename": "My_Part_v3.gcode", "started": False}
    assert b"G28" in fake.uploads[0][1]
    from sqlmodel import Session, select
    from app.db import engine
    from app.models import PrinterJob
    with Session(engine) as s:
        job = s.exec(select(PrinterJob).where(PrinterJob.print_file_id == f["id"])).first()
        assert job and job.model_id == model["id"]


def test_only_gcode_can_be_sent_and_missing_files_are_refused(authed, model, printer):
    fake, p = printer
    sliced = _upload(authed, model["id"], "plate.3mf", _sliced_3mf()).json()
    assert sliced["sendable"] is False
    assert authed.post(f"/api/printers/{p['id']}/send", data={"print_file_id": str(sliced["id"])}).status_code == 400
    assert authed.post(f"/api/printers/{p['id']}/send", data={"print_file_id": "987654"}).status_code == 404
    assert fake.uploads == []


def test_a_finished_print_of_a_kept_file_logs_its_estimated_filament(authed, model, printer):
    fake, p = printer
    f = _upload(authed, model["id"], "benchy.gcode").json()
    authed.post(f"/api/printers/{p['id']}/send", data={"print_file_id": str(f["id"]), "start": "true"})
    from sqlmodel import Session
    from app.db import engine
    with Session(engine) as s:
        fake.moonraker_state = "printing"
        printwatch.poll(s)
        fake.moonraker_state = "complete"
        assert printwatch.poll(s) == [("Kept", "done")]
    log = authed.get("/api/prints", params={"model_id": model["id"]}).json()["items"][0]
    assert log["grams"] == 12.94 and log["source"] == "printer"
