"""Multicolour jobs: every filament of a sliced file counted against the right spool."""
import io
import json
import uuid
import zipfile

import pytest

from app import print_files


def _stl():
    n = 30 + uuid.uuid4().int % 250
    return (f"solid t\nfacet normal 0 0 1\n outer loop\n  vertex 0 0 0\n  vertex {n} 0 0\n  vertex 0 {n} 0\n endloop\nendfacet\nendsolid t\n").encode()


SLICE_INFO = """<?xml version="1.0" encoding="UTF-8"?><config><header><header_item key="X-BBL-Client-Type" value="slicer"/></header>
<plate><metadata key="prediction" value="3600"/><metadata key="weight" value="22.5"/>
<filament id="2" tray_info_idx="GFA00" type="PETG" color="#0000FF" used_m="3.1" used_g="9.5"/>
<filament id="1" tray_info_idx="GFA00" type="PLA" color="#FF0000" used_m="4.5" used_g="13.0"/></plate></config>"""

GCODE = b"""; generated by OrcaSlicer 2.0
G28
; filament used [g] = 13.04, 9.50, 0.00
; filament_type = PLA;PETG;PLA
; filament_colour = #FF0000;#0000FF;#00FF00
; estimated printing time (normal mode) = 1h 0m 0s
"""


def _3mf(tmp_path):
    path = tmp_path / "plate.3mf"
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("Metadata/slice_info.config", SLICE_INFO)
    return path


def test_a_sliced_3mf_lists_each_filament_in_order(tmp_path):
    meta = print_files.parse_3mf(_3mf(tmp_path))
    assert json.loads(meta["filaments"]) == [{"index": 1, "type": "PLA", "color": "#ff0000", "grams": 13.0},
                                             {"index": 2, "type": "PETG", "color": "#0000ff", "grams": 9.5}]


def test_gcode_lists_each_filament_that_was_used(tmp_path):
    meta = print_files.parse_gcode_text(GCODE.decode())
    assert json.loads(meta["filaments"]) == [{"index": 1, "type": "PLA", "color": "#ff0000", "grams": 13.04},
                                             {"index": 2, "type": "PETG", "color": "#0000ff", "grams": 9.5}]          # the unused one is left out
    assert print_files.parse_gcode_text("G28\n; filament used [g] = 7.5\n")["filaments"] == json.dumps([{"index": 1, "type": None, "color": None, "grams": 7.5}])
    assert print_files.parse_gcode_text("G28\n")["filaments"] is None


@pytest.fixture()
def model(authed):
    m = authed.post("/api/library/import", files={"file": (f"mc_{uuid.uuid4().hex[:6]}.stl", _stl(), "application/octet-stream")}).json()
    yield m
    for q in authed.get("/api/queue").json():
        if q["model_id"] == m["id"]:
            authed.delete(f"/api/queue/{q['id']}")
    authed.delete(f"/api/library/models/{m['id']}")


@pytest.fixture()
def printer(authed):
    p = authed.post("/api/printers", json={"name": "MC", "kind": "moonraker", "url": "http://klipper.local:7125", "slot_count": 4}).json()
    yield p
    for q in authed.get("/api/queue").json():
        authed.delete(f"/api/queue/{q['id']}")
    for x in authed.get("/api/printers").json()["printers"]:
        authed.delete(f"/api/printers/{x['id']}")


def _spool(c, material, color, hex_, grams=500):
    return c.post("/api/filament", json={"material": material, "color": color, "color_hex": hex_, "spool_weight_g": 1000, "remaining_g": grams}).json()


def _left(c, spool):
    return next(f for f in c.get("/api/filament").json() if f["id"] == spool["id"])["remaining_g"]


def test_the_kept_file_shows_its_filaments_and_suggests_the_slot_with_the_same_filament(authed, model, printer):
    red, blue = _spool(authed, "PLA", "red", "#ee1111"), _spool(authed, "PETG", "blue", "#0000ee")
    try:
        authed.put(f"/api/slots/{printer['id']}/3", json={"filament_id": red["id"]})
        authed.put(f"/api/slots/{printer['id']}/2", json={"filament_id": blue["id"]})
        kept = authed.post("/api/print-files", data={"model_id": str(model["id"])}, files={"file": ("plate.gcode", GCODE, "application/octet-stream")}).json()
        assert [f["grams"] for f in kept["filament_list"]] == [13.04, 9.5]
        r = authed.get(f"/api/queue/uses-from-file/{model['id']}", params={"printer_id": printer["id"]}).json()
        assert r["file"]["filename"] == "plate.gcode"
        assert [(f["type"], f["suggested_slot"]) for f in r["filaments"]] == [("PLA", 3), ("PETG", 2)]
        no_printer = authed.get(f"/api/queue/uses-from-file/{model['id']}").json()
        assert [f["suggested_slot"] for f in no_printer["filaments"]] == [None, None]
        assert authed.get("/api/queue/uses-from-file/987654").status_code == 404
    finally:
        for s in (red, blue):
            authed.delete(f"/api/filament/{s['id']}")


def test_a_multicolour_job_takes_grams_from_each_spool_when_it_finishes(authed, model, printer):
    red, blue = _spool(authed, "PLA", "red", "#ee1111", 400), _spool(authed, "PETG", "blue", "#0000ee", 300)
    try:
        authed.put(f"/api/slots/{printer['id']}/1", json={"filament_id": red["id"]})
        authed.put(f"/api/slots/{printer['id']}/2", json={"filament_id": blue["id"]})
        item = authed.post("/api/queue", json={"model_id": model["id"], "printer_id": printer["id"], "estimated_minutes": 60,
                                               "uses": [{"slot": 1, "grams": 13}, {"slot": 2, "grams": 9.5}]}).json()
        assert item["estimated_grams"] == 22.5 and json.loads(item["uses"]) == [{"grams": 13.0, "slot": 1}, {"grams": 9.5, "slot": 2}]
        authed.put(f"/api/slots/{printer['id']}/2", json={"filament_id": red["id"]})            # the red spool moved: the job follows the slot
        authed.put(f"/api/slots/{printer['id']}/1", json={"filament_id": blue["id"]})
        authed.patch(f"/api/queue/{item['id']}", json={"status": "done"})
        assert _left(authed, blue) == 287 and _left(authed, red) == 390.5
        log = authed.get("/api/prints", params={"model_id": model["id"]}).json()["items"][0]
        assert log["grams"] == 22.5 and log["filament_id"] == blue["id"]
        assert sorted(u["grams"] for u in json.loads(log["uses"])) == [9.5, 13.0]
    finally:
        for s in (red, blue):
            authed.delete(f"/api/filament/{s['id']}")


def test_uses_can_name_a_spool_directly_and_are_checked(authed, model, printer):
    red = _spool(authed, "PLA", "red", "#ee1111", 100)
    try:
        ok = authed.post("/api/queue", json={"model_id": model["id"], "uses": [{"filament_id": red["id"], "grams": 30}]})
        assert ok.status_code == 200 and ok.json()["estimated_grams"] == 30
        for bad in ([{"grams": 5}], [{"slot": 9, "grams": 5}], [{"filament_id": 987654, "grams": 5}], [{"filament_id": red["id"], "grams": 0}],
                    [{"filament_id": red["id"], "grams": "5"}], "x", [1], [{"filament_id": red["id"], "grams": 5}] * 17):
            body = {"model_id": model["id"], "printer_id": printer["id"], "uses": bad}
            assert authed.post("/api/queue", json=body).status_code == 400, bad
        assert authed.post("/api/queue", json={"model_id": model["id"], "uses": [{"slot": 1, "grams": 5}]}).status_code == 400            # a slot needs the printer
        edited = authed.patch(f"/api/queue/{ok.json()['id']}", json={"uses": [{"filament_id": red["id"], "grams": 12}]}).json()
        assert edited["estimated_grams"] == 12
        assert authed.patch(f"/api/queue/{ok.json()['id']}", json={"uses": None}).json()["uses"] is None
    finally:
        authed.delete(f"/api/filament/{red['id']}")


def test_the_calendar_checks_every_spool_of_a_multicolour_job(authed, model, printer):
    big, small = _spool(authed, "PLA", "big", "#ee1111", 900), _spool(authed, "PETG", "small", "#0000ee", 5)
    try:
        authed.post("/api/queue", json={"model_id": model["id"], "planned_date": "2037-02-03", "uses": [{"filament_id": big["id"], "grams": 10}, {"filament_id": small["id"], "grams": 20}]})
        view = authed.get("/api/calendar", params={"month": "2037-02"}).json()
        entry = view["days"]["2037-02-03"]["planned"][0]
        assert view["short_count"] == 1 and entry["short"]["short_by"] == 15.0 and "small" in entry["short"]["spool"]
    finally:
        for s in (big, small):
            authed.delete(f"/api/filament/{s['id']}")


def test_a_single_spool_job_works_as_before(authed, model, printer):
    red = _spool(authed, "PLA", "red", "#ee1111", 200)
    try:
        item = authed.post("/api/queue", json={"model_id": model["id"], "filament_id": red["id"], "estimated_grams": 25}).json()
        authed.patch(f"/api/queue/{item['id']}", json={"status": "done"})
        assert _left(authed, red) == 175
        assert authed.get("/api/prints", params={"model_id": model["id"]}).json()["items"][0]["uses"] is None
    finally:
        authed.delete(f"/api/filament/{red['id']}")
